version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  zipkindb:
    build: zipkindb
    ports:
      - 3306:3306

  common-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  elk-server:
    build: elk-server
    ports:
      - 5044:5044
      - 5061:5061
      - 4560:4560
      - 9200:9200
      - 9300:9300

  config:
    build: config
    ports:
      - 8888:8888

  zipkin-server:
    build: zipkin-server
    ports:
      - 9411:9411

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  registry:
    build: registry

  gateway:
    build: gateway

  account-service:
    build: account-service
    ports:
      - 6000:6000

  license-service:
    build: license-service
    ports:
      - 6100:6100

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  notification-service:
    build: notification-service
    ports:
      - 8000:8000

  monitoring:
    build: monitoring
